# Generated by Django 3.2.4 on 2021-06-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_listall_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listall',
            name='Stage_name',
            field=models.CharField(choices=[(1, 'Аннулирование'), (2, 'Внесение остатка/выдача перерасхода'), (3, 'Выгрузка'), (4, 'Отражение в учете'), (5, 'Регистрация в учете'), (6, 'Согласование'), (7, 'Установка статуса выгрузки'), (8, 'Утверждение'), (9, 'Формирование'), (10, 'Формирование и выгрузка'), (11, 'Формирование отправки')], max_length=3, verbose_name='Этап'),
        ),
    ]
