# Generated by Django 3.2.4 on 2021-06-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_listall_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listall',
            name='Stage_user',
            field=models.CharField(blank=True, max_length=64, verbose_name='Исполнитель'),
        ),
    ]
