# Generated by Django 3.2.4 on 2021-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_listall_stage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listall',
            name='Stage_user',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Исполнитель'),
        ),
    ]
