# Generated by Django 3.2.4 on 2021-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_listall_stage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listall',
            name='Document_init_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания документа'),
        ),
        migrations.AlterField(
            model_name='listall',
            name='Document_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='listall',
            name='Document_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='listall',
            name='Foiv',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ФОИВ'),
        ),
        migrations.AlterField(
            model_name='listall',
            name='Stage_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения этапа'),
        ),
        migrations.AlterField(
            model_name='listall',
            name='Stage_name',
            field=models.CharField(choices=[(1, 'Аннулирование'), (2, 'Внесение остатка/выдача перерасхода'), (3, 'Выгрузка'), (4, 'Отражение в учете'), (5, 'Регистрация в учете'), (6, 'Согласование'), (7, 'Установка статуса выгрузки'), (8, 'Утверждение'), (9, 'Формирование'), (10, 'Формирование и выгрузка'), (11, 'Формирование отправки'), (12, '')], default=12, max_length=3, verbose_name='Этап'),
        ),
    ]
