# Generated by Django 3.2.4 on 2021-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210629_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listall',
            name='Stage_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Этап'),
        ),
    ]
